CREATE DATABASE lights_ecommerce;
USE lights_ecommerce;

CREATE TABLE CUSTOMERS (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    phoneNumber VARCHAR(15) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    address VARCHAR(180) NOT NULL,
    countryId INT REFERENCES COUNTRIES(id)
);

CREATE TABLE PRODUCTS (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    price FLOAT UNSIGNED NOT NULL,
    stock INT UNSIGNED NOT NULL,
    status BOOLEAN NOT NULL,
    categoryId INT REFERENCES CATEGORIES(id),
    createdBy BIGINT NOT NULL,
    updatedBy BIGINT DEFAULT 'No updated'
);

CREATE TABLE PRODUCT_BY_ORDER(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    quantity INT UNSIGNED NOT NULL,
    salePrice DECIMAL(8, 2) NOT NULL,
    productId BIGINT REFERENCES PRODUCTS(id),
    orderId BIGINT REFERENCES ORDERS(id)
);

CREATE TABLE CATEGORIES(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

-- status: 1. Pago pendiente, pedido creado, 2. Pago confirmado, procesando pedido 3. Pedido despachado 4. Pedido entregado
CREATE TABLE ORDERS(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    status ENUM('pending', 'processing', 'dispatched', 'delivered') NOT NULL,
    totalAmount DECIMAL(8, 2) NOT NULL,
    customerId BIGINT REFERENCES CUSTOMERS(id)
);

CREATE TABLE IMAGES(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    imageURL VARCHAR(255) NOT NULL,
    colorCode VARCHAR(50) NOT NULL,
    color VARCHAR(50) NOT NULL,
    productId BIGINT REFERENCES PRODUCTS(id)
);

CREATE TABLE COUNTRIES(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    deparment VARCHAR(100) NOT NULL
);

CREATE TABLE ORDERS_LOGS(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    previousStatus ENUM('pending', 'processing', 'dispatched', 'delivered') NOT NULL,
    newStatus ENUM('pending', 'processing', 'dispatched', 'delivered') NOT NULL,
    orderId BIGINT REFERENCES ORDERS(id),
    changedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    changedBy BIGINT NOT NULL
);

CREATE TABLE FRAGANCIES(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    productId BIGINT REFERENCES PRODUCTS(id)
);

DROP TABLE IMAGES;